<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
            <div class="footer-black-outer-container">
                <div class="footer-black">
                    <div class="footer-black-inner-container">
                        <div class="footer-links">
                             <a target="_blank" href="/wcsstore/DebenhamsIntSite/faq/en-lt/legal_information/cookie_notice.html" class="footer-link-item"><?= $block->escapeHtml(__('Cookies')) ?></a>
                            <a target="_blank" href="/wcsstore/DebenhamsIntSite/faq/en-lt/legal_information/privacy_policy.html" class="footer-link-item"><?= $block->escapeHtml(__('Privacy')) ?></a>
                            <a target="_blank" href="/wcsstore/DebenhamsIntSite/faq/en-lt/legal_information/general_terms_conditions.html" class="footer-link-item"><?= $block->escapeHtml(__('Terms &amp; Conditions')) ?></a>
                            <a href="javascript:var tmp=window.open('/en-lt/content/legal-disclaimer-pop-up?popup=y','','height=606,width=579,scrollbars=yes,resizable=1',toolbar='no')" class="footer-link-item"><?= $block->escapeHtml(__('Legal Disclaimer')) ?></a>
                        </div>
                        <div class="footer-copyright"><?= $block->escapeHtml(__('Copyright © Debenhams Retail plc. All rights reserved')) ?></div>
                    </div>
                </div>
            </div>
