<?php
/**
 * Copyright © MageKey. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \Magento\Store\Block\Switcher $block */
$_dataHelper = $this->helper(\MageKey\StoresFlags\Helper\Data::class);
?>
<?php if (count($block->getStores())>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
<div class="debs-footer-bottom-outer-container">
                <div class="debs-footer-bottom-container">
                    <div class="debs-footer-bottom">
                        <div class="country-container">
                        	<span>We now deliver to 3 countries worldwide</span>
                        	<div class="country-details">
                            	
								
								
								<div class="switcher language switcher-language-bottom" data-ui-id="language-switcher-bottom" id="switcher-language-bottom<?= /* @noEscape */ $id ?>">
    <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Language')) ?></span></strong>
    <div class="actions dropdown options switcher-options">
        
        
        
        <div class="action toggle switcher-trigger"
             id="switcher-language-trigger<?= /* @noEscape */ $id ?>"
             data-mage-init='{"dropdown":{}}'
             data-toggle="dropdown"
             data-trigger-keypress-button="true">
            <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                <?php if ($currentFlag = $_dataHelper->getCurrentFlag()): ?>
                <span class="flag-icon flag-icon-<?= /* @noEscape */ $currentFlag ?>"></span>
                <span><?= $block->escapeHtml($block->getStoreName()) ?></span>
                
                
                
                <span class="country-change">(Change Country)</span>
            
                
                
                <?php else: ?>
                
                <?php endif; ?>
            </strong>
        </div>
        <ul class="dropdown switcher-dropdown"
            data-target="dropdown">
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                    <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option<?= /* @noEscape */ ($_lang->getFlag() ? ' has-flag' : '') ?>">
                        <a href="#" data-post='<?= /* @noEscape */ $block->getTargetStorePostData($_lang) ?>'>
                            <?php if ($_lang->getFlag()): ?>
                                <span class="flag-icon flag-icon-<?= /* @noEscape */ $_lang->getFlag() ?>"></span>
                            <?php endif; ?>
                            <?= $block->escapeHtml($_lang->getName()) ?>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
        
        
        
    </div>
</div>
								
								
							</div>
                        </div>
                        <div class="card-logos-container">
                        	<a href="/wcsstore/DebenhamsUKSite/faq/our_online_services/payments.html">
								<span></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
<?php endif; ?>
