<?php $order = $block->getOrder() ?>
<?php if ($order->getIsVirtual()) { return ''; } ?>
<?php $agent = $block->getAgent(); ?>
<?php if ( strpos($order->getShippingMethod(), 'smartship') === false ) { return ''; } ?>
<?php if ( strpos($order->getShippingMethod(), 'PO2103') === false ) { return ''; } ?>

<section class="admin__page-section order-view-smartship-agent">
  <div class="admin__page-section-content">
    <div class="admin__page-section-item">
      <div class="admin__page-section-item-title">
        <span class="title"><?= __('Pickup Location') ?></span>
      </div>
      <div class="admin__page-section-item-content">
        <?php if ($agent) { ?>
          <?= $agent->name; ?><br>
          <?= $agent->address; ?><br>
          <?= $agent->postcode; ?> <?= $agent->city; ?><br>
        <?php } else { ?>
          <?= __( 'No pickup location selected.' ); ?>
        <?php } ?>
        <a href="#" class="open-smartship-agent-modal">
          <?php echo __('Change'); ?>
        </a>
      </div>
    </div>
  </div>
</section>

<script type="text/javascript">
  require([
    'jquery',
    'Magento_Ui/js/modal/modal'
  ], function($, modal) {
    $('#smartship-admin-agent-search').modal({
      title: 'Change Pickup Location',
      buttons: [
        {
          text: 'Cancel',
          class: 'action-secondary',
          click: function() {
            this.closeModal();
          }
        },
        {
          text: 'Save',
          class: 'action-primary',
          click: function() {
            $('#smartship-admin-agent-search form').submit();
          }
        }
      ]
    });

    /**
     * Open the modal when clicking the button
     */
    $(document).on('click', '.open-smartship-agent-modal', function(e) {
      e.preventDefault();

      $('#smartship-admin-agent-search').modal('openModal');
    });
  });
</script>

<div id="smartship-admin-agent-search" data-bind="scope:'smartship-admin-agent-search'">
  <!-- ko template: getTemplate() --><!-- /ko -->
  <script type="text/x-magento-init">
  {
    "#smartship-admin-agent-search": {
      "Magento_Ui/js/core/app": {
        "components": {
          "smartship-admin-agent-search": {
            "component": "Markup_Smartship/js/view/admin-agent-search",
            "formAction": "<?= $block->getFormAction(); ?>",
            "formKey": "<?= $block->getFormKey(); ?>",
            "orderId": "<?= $block->getOrder()->getId(); ?>"
          }
        }
      }
    }
  }
  </script>
</div>
