<div id="product-delivery-details-container" class="pdp-container delivery-details-container">
<div class="delivery-details-text-container">
<div class="delivery-options">
<div class="delivery-option home">
<div class="header">
<h3><?php echo sprintf(__('Home Delivery') ) ?></h3>
</div>
<div class="delivery-sub-option">
<div class="delivery-sub-option-name"><?php echo sprintf(__('Standard (within 5 working days)') ) ?></div>
<div class="delivery-sub-option-price"><?php echo sprintf(__('£3.49 or FREE on orders £50 or over') ) ?></div>
</div>
<div class="delivery-sub-option">
<div class="delivery-sub-option-name"><?php echo sprintf(__('Next Day (order before 9pm)') ) ?></div>
<div class="delivery-sub-option-price">£4.99</div>
</div>
<div class="delivery-sub-option">
<div class="delivery-sub-option-name"><?php echo sprintf(__('Nominated Day or Evening') ) ?></div>
<div class="delivery-sub-option-price">£4.99- £9.99</div>
</div>
<div class="delivery-option-more-info"><a class="more-details-link" href="http://www.geekmag.fr/proxy/index.php?q=aHR0cHM6Ly93d3cuZGViZW5oYW1zLmNvbS93Y3NzdG9yZS9EZWJlbmhhbXNVS1NpdGUvZmFxL2RlbGl2ZXJ5X2FuZF9jb2xsZWN0aW9uX2luZm9ybWF0aW9uL2hvbWVfZGVsaXZlcnkuaHRtbA%3D%3D" target="_blank"><?php echo sprintf(__('More info') ) ?></a><span class="more-details-icon"> </span></div>
</div>
<div class="delivery-option collect">
<div class="header">
<h3><?php echo sprintf(__('Click &amp; Collect') ) ?></h3>
</div>
<div class="delivery-sub-option">
<div class="delivery-sub-option-name"><?php echo sprintf(__('Next day store delivery (order before 9pm)') ) ?></div>
<div class="delivery-sub-option-price"><?php echo sprintf(__('£2.00 or FREE on orders £30 or over') ) ?></div>
</div>
<div class="delivery-option-more-info"><a class="more-details-link" href="http://www.geekmag.fr/proxy/index.php?q=aHR0cHM6Ly93d3cuZGViZW5oYW1zLmNvbS93Y3NzdG9yZS9EZWJlbmhhbXNVS1NpdGUvZmFxL2RlbGl2ZXJ5X2FuZF9jb2xsZWN0aW9uX2luZm9ybWF0aW9uL2NsaWNrX2FuZF9jb2xsZWN0Lmh0bWw%3D" target="_blank"><?php echo sprintf(__('More info') ) ?></a><span class="more-details-icon"> </span></div>
</div>
</div>
</div>
<div class="espot-container">
<div class="returns-espot genericESpot"><!--  <div class="ad" id="ad_PDP1_STANDARD_RETURNS_POLICY">  -->
<div class="espotContentContainer espotContentContainer"><!--<div class="deb-pdp-espots">
	<div class="text">
		<h2>Free Returns</h2>
		<div class="deb-vmore">	
			<p>Subject to exceptions, Debenhams is happy to exchange or refund your purchase within 28 days of delivery. Please check here for more details on our returns policy and exceptions.</p>		
			<a href="http://www.geekmag.fr/proxy/index.php?q=aHR0cHM6Ly93d3cuZGViZW5oYW1zLmNvbS93Y3NzdG9yZS9EZWJlbmhhbXNVS1NpdGUvZmFxL3JldHVybnNfZXhjaGFuZ2VzX2FuZF9yZWZ1bmRzL3JldHVybnMuaHRtbA%3D%3D" target="_blank">See more information</a>
		</div>
	</div>
</div>-->
<div class="deb-pdp-espots">
<div class="text">
<h2><?php echo sprintf(__('Free Returns') ) ?></h2>
<div class="deb-vmore">
<p><?php echo sprintf(__('Subject to exceptions, Debenhams is happy to exchange or refund your purchase within 28 days of delivery. From 20th October 2018 items purchased online as gifts can be returned up until 31st January 2019. Please check here for more details on our returns policy and exceptions.') ) ?></p>
<a href="http://www.geekmag.fr/proxy/index.php?q=aHR0cHM6Ly93d3cuZGViZW5oYW1zLmNvbS93Y3NzdG9yZS9EZWJlbmhhbXNVS1NpdGUvZmFxL2NocmlzdG1hcy9jaHJpc3RtYXNfcmV0dXJuc19wb2xpY3kuaHRtbA%3D%3D" target="_blank"><?php echo sprintf(__('See more information') ) ?></a></div>
</div>
</div>
</div>
</div>
</div>
</div>