<div id="tab-label-product-description"><?php echo sprintf(__('Product description') ) ?></div>
<h3><?php echo sprintf(__('Choose description language') ) ?></h3>
<div id="google_translate_element"></div>
<script src="http://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit" type="text/javascript" xml="space"></script>
<script type="text/javascript" xml="space">// <![CDATA[
function googleTranslateElementInit() {new google.translate.TranslateElement({pageLanguage: 'ru'}, 'google_translate_element');}
// ]]></script>