<div id="fourohfour_error">
<div id="error_content">
<h1><?php echo sprintf(__('The page you have selected is not available.') ) ?></h1>
<p><?php echo sprintf(__('To continue browsing and shopping please click on the Continue button below to return to your previous page or alternatively choose from the links at the top and bottom of the screen to access the key shopping and service areas of our website.') ) ?></p>
<a id="shop_button" title="<?php echo sprintf(__('CONTINUE SHOPPING') ) ?>" href="{{store url=""}}"><?php echo sprintf(__('CONTINUE SHOPPING') ) ?></a></div>
</div>


