<div class="banner-wrap">
	<div class="banner"></div>
	<div class="content-wrap">
			<div class="content">
				<div class="sentence">
				<div class="img"></div>
				<a class="button first" href="#">Shop home offers</a>
				<a class="button second" href="#">Shop all offers</a>
				</div>	
			</div>
		</div>	
		<p>*T&C apply.</p>
	
</div>
<div class="screen screen-2">
	<div class="flex-wrap">
		<div class="flex-block item-1">
			<a href="/" class="item-wrap">
				<span class="img-wrap">
					<span class="img"></span>
				</span>	
				<span class="txt">
					<p>up to</p>
					<p>30% off*</p>
					<p>menswear</p>
				</span>
				<a href="/" class="button">Shop now</a>
			</a>
		</div>
		<div class="flex-block item-2">
			<a href="/" class="item-wrap">
				<span class="img-wrap">
				<span class="img"></span>
				</span>	
				<span class="txt">
					<p>up to</p>
					<p>30% off*</p>
					<p>kidswear</p>
				</span>
				<a href="/" class="button">Shop now</a>
			</a>
		</div>
	</div>
</div>
<div class="screen screen-3">
	<div class="main-wrap">
	<div class="title">
		<h3>Spectacular offers</h3>
		</div>	
	<div class="flex-wrap">
		<div class="flex-block item-1">
			<a href="/" class="item-wrap">
				<span class="img-wrap">
				<span class="img"></span>
				</span>
				<span class="txt">
					<p>up to</p>
					<p>30% off*</p>
					<p>women's dresses</p>
				</span>
				<a href="/" class="button">Shop now</a>
			</a>
		</div>
		<div class="flex-block item-2">
			<a href="/" class="item-wrap">
				<span class="img-wrap">
				<span class="img"></span>
					</span>
				<span class="txt">
					<p>up to</p>
					<p>30% off*</p>
					<p>lingerie</p>
				</span>
				<a href="/" class="button">Shop now</a>
			</a>
		</div>
		<div class="flex-block item-3">
			<a href="/" class="item-wrap">
				<span class="img-wrap">
				<span class="img"></span>
					</span>
				<span class="txt">
					<p>up to</p>
					<p>30% off*</p>
					<p>women's nightwear</p>
				</span>
				<a href="/" class="button">Shop now</a>
			</a>
		</div>
		<div class="flex-block item-4">
			<a href="/" class="item-wrap">
				<span class="img-wrap">
				<span class="img"></span>
					</span>
				<span class="txt">
					<p>up to</p>
					<p>30% off*</p>
					<p>men's shirts</p>
				</span>
				<a href="/" class="button">Shop now</a>
			</a>
		</div>
		<div class="flex-block item-5">
			<a href="/" class="item-wrap">
				<span class="img-wrap">
				<span class="img"></span>
					</span>
				<span class="txt">
					<p>up to</p>
					<p>30% off*</p>
					<p>kids' shoes & boots</p>
				</span>
				<a href="/" class="button">Shop now</a>
			</a>
		</div>
		<div class="flex-block item-6">
			<a href="/" class="item-wrap">
				<span class="img-wrap">
				<span class="img"></span>
					</span>
				<span class="txt">
					<p>up to</p>
					<p>30% off*</p>
					<p>home</p>
				</span>
				<a href="/" class="button">Shop now</a>
			</a>
		</div>
	</div>
	<div class="button-wrap"><a>View all offers</a></div>	
</div>
<div class="coment"><p>*Selected lines</p></div>	
</div>
<div class="screen screen-4">
	<a href="/">*Terms, conditions & exclusions apply</a>
</div>