<div class="banner-wrap">
	<div class="banner"></div>
	<div class="content-wrap">
			<div class="content">
				<div class="sentence">
				<div class="img"></div>
				<a class="button first" href="#">Shop home offers</a>
				<a class="button second" href="#">Shop all offers</a>
				</div>	
			</div>
		</div>	
		<p>*T&C apply.</p>
	
</div>
<div class="screen screen-2">
	<div class="flex-wrap">
		<div class="flex-block item-1">
			<a href="/" class="item-wrap">
				<span class="img"></span>
				<span class="txt">
					<p>up to</p>
					<p>30% off*</p>
					<p>menswear</p>
				</span>
				<a href="/">Shop now</a>
			</a>
		</div>
		<div class="flex-block item-2">
			<a href="/" class="item-wrap">
				<span class="img"></span>
				<span class="txt">
					<p>up to</p>
					<p>30% off*</p>
					<p>kidswear</p>
				</span>
				<a href="/">Shop now</a>
			</a>
		</div>
	</div>
</div>