<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div id="cfs_header">          
</div>
<div class="layout-container layout-container-background cartempty" id="cfs_section_body">
	<div id="cfs_section">
		<div id="cfs_body960">
			<div id="cfs_body920">
				<div class="empty-bag-content">
					<div class="img">
						<div></div>
					</div>
					<span><?= $block->escapeHtml(__('Your bag is empty.')) ?></span>
					<div class="question"><p><?= $block->escapeHtml(__('Why not treat yourself to a little something?')) ?></p></div>
					<a class="button secondary-cta continue-shopping" title="<?= $block->escapeHtml(__('Continue shopping')) ?>" href="%1">
						<span><strong><?= $block->escapeHtml(__('Continue shopping')) ?></strong></span>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
