<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div id="cfs_header">      
         <h1>My shopping bag</h1>
     
</div>
<div class="layout-container layout-container-background cartempty" id="cfs_section_body">
	<div id="cfs_section">
		<div id="cfs_body960">
			<div id="cfs_body920">
				<div class="empty-bag-content">
					<span>Your shopping bag is empty.</span>
					<a class="button secondary-cta continue-shopping" title="Continue shopping" href="%1">
						<span><strong>Continue shopping</strong></span>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
